repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(src)
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    types_or: [c++, c]
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
- repo: local
  hooks:
    - id: towncrier-check
      name: towncrier fragment check
      entry: pixi run towncrier
      language: system
      pass_filenames: false
      always_run: true
      args: ["check", "--compare-with", "origin/main"]
    - id: cppcheck
      name: cppcheck
      entry: cppcheck
      language: system
      types_or: [c++, c]
      args: ["--error-exitcode=0"]
    # - id: cpplint
    #   name: cpplint
    #   entry: cpplint
    #   language: system
    #   types_or: [c++, c]
    #   args: ["--filter=-whitespace/comments,-runtime/references,-whitespace/indent,-runtime/int,-build/c++11"]
    - id: meson-format
      name: meson format
      entry: meson
      language: system
      types: [meson]
      files: meson\.build$
      args: ["format", "-i"]
    - id: nickel-format
      name: nickel format
      entry: pixi r -e cigen nickel
      language: system
      files: \.ncl$
      args: ["format"]
