name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildpixi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Install environment
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: "v0.62.1"
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Build and Test
        shell: pixi run bash -e {0}
        run: |
          meson setup bbdir -Dwith_tests=True -Dwith_rpc=False
          meson test -C bbdir --print-errorlogs
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          activate-environment: true
      - name: RPC integration
        shell: pixi run bash -e {0}
        run: |
          meson setup bbdir -Dwith_tests=True -Dwith_rpc=True
          meson compile -C bbdir
          meson test -C bbdir --print-errorlogs
          uv pip install numpy pycapnp
          uv run python tests/rpc_integ.py --server-bin bbdir/CppCore/rgpot/rpc/potserv
      - name: CMake integration
        shell: pixi run bash -e {0}
        run: |
          cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DPOTLIB_BUILD_TESTS=True \
                -DPOTLIB_BUILD_EXAMPLES=True \
                -DPOTLIB_WITH_RPC=True \ 
          cmake --build build -j
          ctest --test-dir build
          uv pip install numpy pycapnp
          uv run python tests/rpc_integ.py --server-bin build/potserv
