name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildpixi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Install environment
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: 'v0.62.1'
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Build and Test
        shell: pixi run bash -e {0}
        run: |
          meson setup bbdir -Dwith_tests=True
          meson test -C bbdir
